-- CreateEnum
CREATE TYPE "ProductCatalogStatus" AS ENUM ('DRAFT', 'PENDING_REVIEW', 'CHANGES_REQUESTED', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "ProductAvailability" AS ENUM ('IN_STOCK', 'OUT_OF_STOCK', 'COMING_SOON', 'ON_DEMAND');

-- AuditLog userAgent
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;

-- Product catalog editor fields (additive)
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shortDescEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shortDescAr" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "keyFeatures" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "whatsInBox" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "catalogStatus" "ProductCatalogStatus" NOT NULL DEFAULT 'DRAFT';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "availability" "ProductAvailability" NOT NULL DEFAULT 'IN_STOCK';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "priceUsd" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "costPrice" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "salePrice" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "saleStartAt" TIMESTAMP(3);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "saleEndAt" TIMESTAMP(3);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "lowStockThreshold" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "prepTimeDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "metaTitleEn" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "metaTitleAr" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "metaDescEn" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "metaDescAr" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoKeywords" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "weightKg" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "dimLengthCm" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "dimWidthCm" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "dimHeightCm" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "requiresSpecialHandling" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "excludedProvinces" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "internalNotes" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "sourceSupplier" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "purchaseInvoiceRef" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "createdById" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3);
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "reviewNotes" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Product_slug_key" ON "Product"("slug");

UPDATE "Product" SET "catalogStatus" = 'PUBLISHED' WHERE "published" = true AND "deletedAt" IS NULL;
UPDATE "Product" SET "catalogStatus" = 'ARCHIVED' WHERE "deletedAt" IS NOT NULL;

-- ProductImage responsive variants + alt text
ALTER TABLE "ProductImage" ADD COLUMN IF NOT EXISTS "urlW200" TEXT;
ALTER TABLE "ProductImage" ADD COLUMN IF NOT EXISTS "urlW400" TEXT;
ALTER TABLE "ProductImage" ADD COLUMN IF NOT EXISTS "urlW800" TEXT;
ALTER TABLE "ProductImage" ADD COLUMN IF NOT EXISTS "altTextAr" TEXT;
ALTER TABLE "ProductImage" ADD COLUMN IF NOT EXISTS "altTextEn" TEXT;
ALTER TABLE "ProductImage" ADD COLUMN IF NOT EXISTS "isCover" BOOLEAN NOT NULL DEFAULT false;

-- ProductComment
CREATE TABLE IF NOT EXISTS "ProductComment" (
    "id" TEXT NOT NULL,
    "productId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProductComment_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "ProductComment_productId_createdAt_idx" ON "ProductComment"("productId", "createdAt");
CREATE INDEX IF NOT EXISTS "ProductComment_userId_idx" ON "ProductComment"("userId");
ALTER TABLE "ProductComment" ADD CONSTRAINT "ProductComment_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProductComment" ADD CONSTRAINT "ProductComment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "AdminUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
